### ISSUE TITLE
Import Monster doesn't work anymore

### ISSUE THREAD

**Issue by Potato-Tyrant** [astranauta/astranauta.github.io#104]
First of all I don't know if this issue belongs to here or to the R20 one.
Anyways, clicking on Import Monster on roll20 does nothing anymore, except moving you to your journal page. Import Items and Import Spells do work as usual.

**Comment by MrLabRat** [comment]
This belongs to the other repository. And it's a known issue. 👍 

https://github.com/astranauta/5etoolsR20/issues/6

**Comment by ariestae** [comment]
bestiary.json
Line 23716

```json
"Imps can be found in the service to mortal spellcasters, acting as advisors, spies, and familiars. An imp urges its master to acts of evil, knowing the mortal's soul is a prize the imp might ultimately claim. Imps display an unusual loyalty to their masters, and an imp can be quite dangerous if its master is threatened. Some such imps have the following trait.",
```

Remove `,` at the end of the line.

**Comment by MrLabRat** [comment]
I'll try that!

**Comment by Mooogus** [comment]
We have to wait for the pull request before we can import?
