### ISSUE TITLE
Necklace of Fireballs and Holy Water (flask) typo

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#105]
For NoF: "You can use an action to detach a bead and throw it up to 6 feet away." should be 60 feet. Being able to throw a 20 radius spell only 6 feet sounds like a bad time.

Holy Water has: "\n\tA cleric or paladin may create holy water by performing a special ritual." I don't know what \n\ is about.

**Comment by MrLabRat** [comment]
Solved with #106

**Comment by astranauta** [comment]
Merged.
