### ISSUE TITLE
Possessed Pillar & Creepy Doll from the Bestiary have missing and mixed up stats along with stat bonuses

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#121]
Possesed Pillar looks like this with missing and mixed stats:
STR | DEX | CON | INT | WIS | CHA
-- | -- | -- | -- | -- | --
20 (+5) | 8 (−1)  19 () | 3 (−4)  11 () | 1 (−5) () | 10 () | 10 ()

When it should be:
STR DEX CON INT WIS CHA
20 (+5) 8 (−1) 19 (+4) 3 (−4) 11 (+0) 1 (−5)

Creepy Doll has the same problem:
STR | DEX | CON | INT | WIS | CHA
-- | -- | -- | -- | -- | --
6 (−2) 14 () | 13 (+1) | 12 (+1) | 11 (+0) | 10 (+0) | (-5)

Should be:
STR DEX CON INT WIS CHA
6 (−2) 14 (+2) 13 (+1) 12 (+1) 11 (+0) 10 (+0)

**Comment by MrLabRat** [comment]
Will fix this in a moment!

**Comment by MrLabRat** [comment]
Fixed with my last commit!
