### ISSUE TITLE
Wight damage immunities/resists incorrect.

### ISSUE THREAD

**Issue by Cmayeux** [astranauta/astranauta.github.io#122]
The Wight stat block currently shows: 
Damage Immunities: necrotic, bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered. 
Condition Immunities: Poison

The Monster Manual has it listed as: 
Damage **Resistances**: necrotic, bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered. 
Damage Immunities: **Poison**
Condition Immunities: **Exhaustion**, Poison

Please correct, thank you!

**Comment by MrLabRat** [comment]
Fixed this in #120
