### ISSUE TITLE
Necklace of Fireballs tooltip incorrect.

### ISSUE THREAD

**Issue by Cmayeux** [astranauta/astranauta.github.io#123]
Currently reads:
Necklace of Fireballs
Wondrous Item, Rare
1 lb.

This necklace has 1d6 + 3 beads hanging from it. You can use an action to detach a bead and throw it up to **6** feet away. When it reaches the end of its trajectory, the bead detonates as a 3rd-level fireball spell (save DC 15).
You can hurl multiple beads, or even the whole necklace, as one action. When you do so, increase the level of the fireball by 1 for each bead beyond the first.

The 6 feet should be 60. Players were very confused by that one!

Thank you.

**Comment by MrLabRat** [comment]
Is that so? I just checked it and it seems alright.

https://astranauta.github.io/items.html#Necklace%20of%20Fireballs

**Comment by Cmayeux** [comment]
That is it, ours gets updated monthly. Thank you!

**Comment by MrLabRat** [comment]
No problem! You can always check up my [fork](https://github.com/MrLabRat/mrlabrat.github.io) for the latest updates. 👍
