### ISSUE TITLE
Additional Properties of Armor

### ISSUE THREAD

**Issue by DeltaVenom** [astranauta/astranauta.github.io#125]
The PHB notes things such as a specific Strength requirement to wear Armor.
Certain Armor gives the wearer disadvantage on Stealth as well.
These Properties are not listen on the relevant Armors.

**Comment by MrLabRat** [comment]
Because the Strength requirement to wear Armor is a common rule. It isn't a property of the armor.
Check https://astranauta.github.io/rules.html#Armor

**Comment by DeltaVenom** [comment]
That is true. However, having the strength requirement and stealth disadvantage on the actual armor that it applies to would be more user friendly.
Plus, there are Medium armors and even a Light armor that give disadvantage on Stealth, as well as a heavy armor (Ring mail) that does not have a strength requirement.

**Comment by MrLabRat** [comment]
Since I'm not the owner of the website I'd like @astranauta to have a word on this matter.

**Comment by astranauta** [comment]
I agree with Delta here, it should be listed on the armor, since we don't have a table of armor to look at that would list that.

**Comment by MrLabRat** [comment]
@astranauta 

What about this -> https://astranauta.github.io/rules.html#Armor

**Comment by TheGiddyLimit** [comment]
I was thinking the same thing - in the PHB, the information's all in one table; I think not having it on the entries in the Items page is confusing. 
It was on my to-do list, but I forgot about it - I'll get it done.

**Comment by MrLabRat** [comment]
Thanks @TheGiddyLimit!

**Comment by MrLabRat** [comment]
Thanks for solving this! How did you fix it?

**Comment by TheGiddyLimit** [comment]
Turned out the data was already in the JSON, it just needed displayed. See lines 354-359 here:
https://github.com/astranauta/astranauta.github.io/blob/a8876bdadbb49c6612fb14d6d9b1731ef8cdb772/js/page-items.js#L354

**Comment by MrLabRat** [comment]
That's great! I was wondering about the mithral armors. (They are an exception to the rules)

Great job!
