### ISSUE TITLE
prevent resizing table rows

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#126]
Hi, great site, one issue I'm having is when mousing over the Spells table, the rows expand and contract wildly (to show all classes), making selection difficult. Since the spells are not sortable by class, could that column be removed entirely? This is an issue for all tables, not just spells, but that's where it's very noticeable.

**Comment by MrLabRat** [comment]
The spells are sort-able by class you just to select your desired class in the "All Classes" filter

**Comment by aeosynth** [comment]
The class sort button is disabled for me whether or not I have a class selected in the filter.

**Comment by MrLabRat** [comment]
I believe that the table is needed in order for the javascript to filter the spells.

**Comment by aeosynth** [comment]
The column can be hidden without being removed, or instead of hiding it, it could be made to not expand.

**Comment by TheGiddyLimit** [comment]
I vote for hiding it, it looks much better without it. 
The information's still there in the filters/at the bottom of the stats block, and the column in the table was downright unreadable anyway.
The Javascript works either way, provided it's hidden with CSS (can still search e.g. "Bard" and get all the Bard spells).
I'll submit a pull request.

**Comment by MrLabRat** [comment]
Solved!
