### ISSUE TITLE
PSK - Missing feats and creatures

### ISSUE THREAD

**Issue by TheGiddyLimit** [astranauta/astranauta.github.io#132]
https://media.wizards.com/2017/downloads/magic/Plane-Shift_Kaladesh.pdf

Feats:
-Quicksmithing
-Servo Crafting

Creatures:
-Gremlin
-Sky Leviathan
-Servo

**Comment by MrLabRat** [comment]
Will work on it!

**Comment by MrLabRat** [comment]
This should be solved with #135
