### ISSUE TITLE
history navigation

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#137]
when selecting a spell, the url changes. i would like to navigate through my history and see the spell my url shows.

**Comment by astranauta** [comment]
So open up your history? This doesn't sound like an issue with our website.

**Comment by aeosynth** [comment]
The issue is that the url doesn't match up with the spell shown. I go to the spell list, click aid, url shows `#aid`. click alarm, url shows `#alarm`. click back button, url shows `#aid`, but the spell shown is still alarm. tested on linux/chromium.

**Comment by MrLabRat** [comment]
This is a minor issue, you can just reload the page and get the spell to load.

**Comment by aeosynth** [comment]
yes there are workarounds, but i'm making a feature request. you can close this issue if you like.

**Comment by astranauta** [comment]
I'm not sure that we're able to provide this service for you, I'm sorry. It looks like you're enjoying the website though, so I encourage you to not let this come between us. Sorry we're not able to help out.

**Comment by aeosynth** [comment]
would you accept a pull request providing this service?
