### ISSUE TITLE
[style] decide on tabs vs spaces

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#142]
tabs and spaces are both used for indentation in a single file (`page-spells.js` at least)

**Comment by TheGiddyLimit** [comment]
I vote spaces.

**Comment by aeosynth** [comment]
oh if we're voting i would go for 2 spaces. thought it would be fiat.

**Comment by MrLabRat** [comment]
I prefer tabs, they keep things more organized.

**Comment by TheGiddyLimit** [comment]
Well that looks like a 2-2 tie. @astranauta as the governing body, would you care to make a deciding vote?

**Comment by astranauta** [comment]
Tabs are cleaner.

**Comment by TheGiddyLimit** [comment]
See #145 👌
