### ISSUE TITLE
Tortle Package new additions

### ISSUE THREAD

**Issue by TheGiddyLimit** [astranauta/astranauta.github.io#144]
For reference:
- [x] Tortle race
- [ ] 5 new monsters

**Comment by TheGiddyLimit** [comment]
Relatedly, I get permission to assign issues ( @astranauta or @MrLabRat )? I'd like to be able to self-assign stuff so you'd know I was working on it. Never had to administer a GitHub repo, I don't know if that's possible.

**Comment by MrLabRat** [comment]
Only @astranauta can do that :/

**Comment by MrLabRat** [comment]
Solved with #159
