### ISSUE TITLE
es6+ features?

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#157]
is there a minimum browser version we are targeting, or can we use all javascript features available in latest stable chrome/firefox (eg `const/let`) ?

also if we can use `const/let`, could we decide on which to use by default? i would prefer `const` for everything, with `let` used to explicitly tag mutability

**Comment by TheGiddyLimit** [comment]
To be honest, I didn't realise how new they were, but I think ES6 is fine. It's hardly cutting edge, and I don't think we're worried about catering to exceedingly old software.

Agreed, I'm all for `const` for everything and `let` where mutability is required.

**Comment by aeosynth** [comment]
at this point they're not really new at all, but there's newer stuff like `await/async` is in es2017, which i'm not sure if everyone is ok with using.

**Comment by TheGiddyLimit** [comment]
I think sticking to ES6 should be fine, unless we have good reason to use anything newer.

**Comment by astranauta** [comment]
Agreed. Closed.
