### ISSUE TITLE
Spell filters stopped working

### ISSUE THREAD

**Issue by Sarkoptesmilbe** [astranauta/astranauta.github.io#164]
At first only filtering by spell level stopped doing anything (I think around the time psionics were added), but now it's every category (sources, levels, schools...).

**Comment by MrLabRat** [comment]
What do you mean? It's working just fine here.

**Comment by Sarkoptesmilbe** [comment]
I checked with another browser and got the same issue. Weird. Must be my machine, then. Sorry for the trouble.

**Comment by MrLabRat** [comment]
No problem!
