### ISSUE TITLE
Bastet Temple Cat's Type

### ISSUE THREAD

**Issue by FTgremlin** [astranauta/astranauta.github.io#17]
Much to my dismay, Bastet Temple Cats are **Monstrosities**, not **Beasts**
My druid was unable to turn into one. To prevent others from making this mistake, that should be changed.

**Comment by FTgremlin** [comment]
[PR](https://github.com/astranauta/astranauta.github.io/pull/18) submitted

**Comment by astranauta** [comment]
See comment on pull request.

**Comment by FTgremlin** [comment]
The book I have in front of me states that Bastet Temple Cats are **Monstrosities**, not **Beasts**.
Upon Googling, common consensus says that they are **Beasts**, not **Monstrosities**.
Wtf.

**Comment by FTgremlin** [comment]
Yep:
http://dndbits.com/monsters.php --> states they are **monstrosities**. The physical copy of the book states that they are, too.

Just checked the errata. My suspicions were confirmed.

<img width="352" alt="screen shot 2017-04-11 at 01 35 09" src="https://cloud.githubusercontent.com/assets/12858421/24887868/2180ff78-1e57-11e7-9990-ee9e22066bb6.png">

**Comment by FTgremlin** [comment]
This has now been resolved, as part of the merged WIP PR. 🤣

**Comment by astranauta** [comment]
Alrighty -- For the future, please link the eratta you'd like to specify changes from
