### ISSUE TITLE
multiple select

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#178]
i'd like to select multiple sources from a table, eg all spells from both the PHB and SCAG.

**Comment by MrLabRat** [comment]
https://www.dndbeyond.com/spells like on this website?

**Comment by aeosynth** [comment]
that's the general idea, yeah

**Comment by TheGiddyLimit** [comment]
I was in the process of appropriating some code for that, quick fiddle [here](http://jsfiddle.net/r4h9p3ba/1/). Still very WIP, need to figure out how to pack all the filters into one button (nested menus), and then give it some CSS, but that's the plan.
