### ISSUE TITLE
Issue with monster import

### ISSUE THREAD

**Issue by McThyzer** [astranauta/astranauta.github.io#179]
I assume parsing issues?

i.e. the Empyrean:

- actions: most information is simply dumped into action description
- legendary actions: (unknown number)
- saving throws & skills are completely missing

**Comment by MrLabRat** [comment]
It seems ok for me. Try deleting the monster from the sidebar and re-import it.

**Comment by McThyzer** [comment]
![scrn-280109561716](https://user-images.githubusercontent.com/1474140/30977216-29013c62-a477-11e7-9898-27b036341a49.png)

Reinstalled the 5eRoll20 script (had mine modified, because I prefer the tokens to be a little different) and removed the Empyrian and reimported him... Still looks like that. The problem is with *every* creature, that the action text block is dumped into its description I simply use the Empyrian as an example.

**Comment by MrLabRat** [comment]
How do I get that to show up? I don't use Roll20 much.

**Comment by MrLabRat** [comment]
Huh @McThyzer? @TheGiddyLimit do you know that?

**Comment by TheGiddyLimit** [comment]
Might be something to do with the recent Roll20 character sheet overhaul. 

I _think_ the view screencapped above can be accessed by (once the import completes) by opening any monster from the Journal, and clicking the Character Sheet tab.

**Comment by McThyzer** [comment]
You mean the monster statblock? After you import the monster, you can open it in the righthand sidebar, under the journal tab. 

You see a "Monster" folder with dozens of subfolders for the creature types.  If you click on a creature it opens its statblock.

## I have solved at least some issues myself by modifying the 5etoolsR20 script as follows:

- For saving throws to show up:
  - I removed the `character.attribs.create({ name: "npc_saving_flag", current: 1});`
  - and changed  `name: "npc_" + save[0].toLowerCase() + "_save",` to `name: "npc_" + save[0].toLowerCase() + "_save_base",`

- For having skills show up:
  - I again removed the `character.attribs.create({ name: "npc_skills_flag", current: 1});`
  - And I changed `if (data.skill instanceof Array) {
                                skills = data.skill;
                            } else {
                                skills = data.skill.split(", ");
                            }` to `if (data.skill instanceof Array) {
                                skills = data.skill[0].split(", ");
                            }`

There are dozens of attributes unnecessarily set, atleast as far as I can see it... currently working on fixing the display of attack actions! Will report back.

**Comment by TheGiddyLimit** [comment]
You're a hero @McThyzer

**Comment by McThyzer** [comment]
My previous skill fix does not display "multi-worded" skills... so I replaced the name of the attribute to the following:

`name: "npc_" + $.trim(skill[1]).toLowerCase().replace(/ /g,"_") + "_base",` 

This should work

**Comment by McThyzer** [comment]
There also seems to be a problem (with the new OGL Sheet) regarding the ability scores. To fix that, one has to add "_base" to all of the main abilities, as follows:

	character.attribs.create({
		name: "strength_base",
		current: data.str
	});
	character.attribs.create({
		name: "dexterity_base",
		current: data.dex
	});
	character.attribs.create({
		name: "constitution_base",
		current: data.con
	});
	character.attribs.create({
		name: "intelligence_base",
		current: data.int
	});
	character.attribs.create({
		name: "wisdom_base",
		current: data.wis
	});
	character.attribs.create({
		name: "charisma_base",
		current: data.cha
	});

Displaying of range and target in the sheet:

	character.attribs.create({
		name: "repeating_npcaction_" + newRowId + "_attack_range",
		current: attackrange
	});
	character.attribs.create({
		name: "repeating_npcaction_" + newRowId + "_attack_target",
		current: attacktarget
	});

**Comment by TheGiddyLimit** [comment]
Could you please submit the updates as a pull request to the other repo?

**Comment by McThyzer** [comment]
Okay, I can do that when I am finished.

**Comment by Konahrik13** [comment]
Is the Shaped sheet different enough that the above fixes won't work? I've noticed at least one problem (Incorrect to no AC.) and I'm not sure is anything else is wrong.

**Comment by McThyzer** [comment]
I never used the shaped sheet, but the ogl sheet differentiates between "ac" which is calculated by "10+dex" and is modified by stuff on the *player sheet*. And the "npc_ac" which is the correct value.

**Comment by MrLabRat** [comment]
Fixed?
