### ISSUE TITLE
Mind Flayer items

### ISSUE THREAD

**Issue by TheGiddyLimit** [astranauta/astranauta.github.io#206]
From @Temp345

"The mind flayers related magic items (VGM) all have the AC value wrong (all +1).
For instance, Mind Carapace Plate Mail's AC should be 18, not 19."

**Comment by MrLabRat** [comment]
How is that? The VGM doesn't specify the AC it just says Any heavy Armor.

**Comment by TheGiddyLimit** [comment]
This:
https://astranauta.github.io/items.html#mind%20carapace%20plate%20armor
Lists the AC as 19, it should be 18. The other "Mind Carapace" armours are similarly wrong.

**Comment by MrLabRat** [comment]
But still, where did you see that it has 18 AC? The book doesn't say anything.

**Comment by MrLabRat** [comment]
#207 should fix this!

**Comment by TheGiddyLimit** [comment]
Took you long enough 😉

**Comment by MrLabRat** [comment]
I was just browsing and got distracted 👍
