### ISSUE TITLE
Monster Import Error

### ISSUE THREAD

**Issue by da3mon-01** [astranauta/astranauta.github.io#211]
Hi! 

I noticed some errors when trying to import monsters, the page where you select what you want to import doesnt show up for me, in either firefox or chrome.

The log has the following:
```
> Exception  SyntaxError: JSON.parse: expected double-quoted property name at line 47506 column 4 of the JSON data
Veremnyomkövetés:
success@eval:481:65
k@https://app.roll20.net/js/jquery.1.8.2.min.js:2:16915
fireWith@https://app.roll20.net/js/jquery.1.8.2.min.js:2:17707
y@https://app.roll20.net/js/jquery.1.8.2.min.js:2:80802
d@https://app.roll20.net/js/jquery.1.8.2.min.js:2:86374
```

**Comment by MrLabRat** [comment]
Yeah! I'm working on it!

**Comment by MrLabRat** [comment]
That happened due to the recent changes in the bestiary database and missed some things during the cleanup.
