### ISSUE TITLE
Improved Attribute Point-Buy Calculator

### ISSUE THREAD

**Issue by MrLabRat** [astranauta/astranauta.github.io#217]
It would be nice if our current point-buy calculator had a way to choose a specific race and use it's attributes eg. Aarakokra (+2 Dex, +1 Wis)

Check [this](http://1-dot-encounter-planner.appspot.com/point-buy-calculator.html) website for reference.

**Comment by aeosynth** [comment]
i'm working on this

**Comment by aeosynth** [comment]
done with #219
