### ISSUE TITLE
json requests

### ISSUE THREAD

**Issue by aeosynth** [astranauta/astranauta.github.io#220]
~~'choose other' racial stats are not supported, eg the half-elf should not get CHA as a +2 and a +1 racial bonus.~~

![half-elf](https://cdn.discordapp.com/attachments/363686096598597644/365588891777892352/halfelf.png)

~~feral tiefling is the only race with a 'predefined' key, it would be nice if instead it were a 'choose 1 from DEX or CHA', along with a number stating the bonus. it might look something like this:~~

```
"ability":
{
  "int": "1",
  "choose": [
    {
      "from" ["dex", "cha"],
      "count": 1,
      "bonus": 2
    }
  ]
}
```

another thing, the 'choose' array is a one element array; we could get rid of the array and make 'choose' point to the object

edit: also `racedata` has a single element, `compendium`. could `compendium` be upgraded into `racedata` ?

**Comment by TheGiddyLimit** [comment]
"Choose" is an array in case a race comes along where you get to choose multiple times. It's redundant right now, but the idea is to over-engineer the data, and then under-engineer the code. It's easier to expand the code later than it is to change the data format which will break all the code that relies on it. Changing one JSON file can break any number of scripts; changing one script should not break any other. Therefore, the less chance of needing to change the JSON, the better. Plus, it's fuckin harmless, leave it alone 😘

Rant aside, please do continue to call out my bullshit, many things are far from optimal.

As for the `racedata` and `compendium` thing, most of the JSON files are structured like that, the reasoning lost in the mists of time. Fixing it is more hassle than it's worth, for me. But by all means, if it's really bothering you, go for it.

**Comment by TheGiddyLimit** [comment]
And I see in Discord you've perhaps cottoned onto the character builder thing - that is kinda my eventual goal with any JSON restructuring; not so _I_ can make a character builder, but to allow someone else to do it as easily as possible. The point-buy calc you made would have been a pain in the ass to do before, I imagine, when the ASI data was muddled in with the text - enabling that sort of cool shit is what I'm all about here. So keep the suggestions coming.
