### ISSUE TITLE
Item List: Minor Fixes (rarity)

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#233]
**Wukka Nuts** and **Dancing Monkey Fruit** listed as magic items.
Well, not sure if this is a mistake, they are magical in a way,
maybe it's the "Adventuring gear" type that puts me off
and should be changed? On the other hand, **ryath root**
is listed as a mundane item and seems as magical as wukka nuts.
I don't know, I don't have a strong opinion about which choice is better,
but it should be consistent.

----

Many magical items (especially from adventures) have "none" as rarity.

Note: I don't know if the same field that specifies the rarity when the objects
are listed is the same used in their description, so be careful not to have to
fix each object twice.

I think to some of those you could set a rarity, e.g. **Spiked Armor of
Radiant Resistance** could be **rare** as **Breastplate of Radiant Resistance**.
EDIT: the spiked armor itself is rare (arguable, see below), so any magical object
using it as base shouldn't have a lesser rarity (if any) ??

I hope this list is exhaustive (and I didn't make mistakes).

### RoT/HotDQ
All [color] **Dragon Mask**s are legendary
Hazirawn is legendary
Insigna of Claws is uncommon
Wand of Winter is rare
Draakhorn is unique (does "unique" appear in other adventures other than RoT?)
Mask of the Dragon Queen is unique (does "unique" appear in other adventures other than RoT?)
### CoS
Blood Spear is uncommon
Gulthias Staff is rare
Saint Markovia's Thighbone is rare
Sunsword is legendary
### LMoP
Spider Staff and Staff of Defense don't specify a rarity
### OotA
Dawnbringer is legendary
Piwafwi is uncommon
Piwafwi of Fire Resistance is rare
Spell Gem's rarity varies from uncommon to legendary (depends on the spell it stores)
Wand of viscid globs is rare
### PotA
Devastation Orbs are very rare
Seeker dart is uncommon
Storm boomerang is uncommon
Weird tank is rare
Wingwear is uncommon
Lost Crown of Besilmer is legendary
Orcsplitter is legendary
Drown is legendary
Ironfang is legendary
Tinderstrike is legendary
Windvene is legendary
### SCAG
The spiked armor item description says it's rare but I don't know if
that's a good enough indication to officially set its rarity.
### VGM
> Mind flayers objects' rarity can only be guessed (uncommon?).

EDIT: Forgot to remove this line when I found out that they indeed have a specific rarity.
Mind Blade (any sword) is rare
Mind Carapace Armor (any heavy) is uncommon
Mind Lash is rare
Shield of Far Sight is rare

**Comment by TheGiddyLimit** [comment]
Perhaps we list unknown rarity items as "unknown," anything else is pure opinion, which I don't think we want in our data. Excellent list, though, great stuff.

I'm not going to have time to go through this for a while, though, on vaycay -- @MrLabRat ?

**Comment by MrLabRat** [comment]
On it! @TheGiddyLimit @Temp345

**Comment by MrLabRat** [comment]
This should be solved now! 👍
