### ISSUE TITLE
Spells: casting time filter

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#235]
Now, this sounds like a request, but it's just an observation.

I think the casting time would be a useful filter for spells.

Would its implementation be a lot of work? It's already in the
spell description so maybe it could be a trivial change?

**Comment by DBAWiseMan** [comment]
In Cleanup #153 there's a task, "Add missing note to City Cleric domain (asterisk reference)". I then started to look at those Modern Magic spells and found some errors, e.g. Infallible Relay is level 1 not 3 (which I'll fix) and also a new tag, "technomagic".
I'll look at appropriately including the technomagic tag and will see what can easily be done to filter, and maybe even sort, by casting time.
