### ISSUE TITLE
Convert filters to new format

### ISSUE THREAD

**Issue by TheGiddyLimit** [astranauta/astranauta.github.io#237]
Once #236 gets merged, with the new filtering code

**Comment by aeosynth** [comment]
what is the new format?

**Comment by TheGiddyLimit** [comment]
See the psionics page. Although you broke the "reset" with your "DRY search" pull.

**Comment by aeosynth** [comment]
what should i be looking at in psionics

**Comment by TheGiddyLimit** [comment]
Yeah, to enable your "multiple filtering" suggestion. Obviously a bit pointless on the psionics page, but (hopefully) the code is reusable. Feel free to hook it up to the other pages - I'll try get the spells page done soon, but that might be a long "soon."

**Comment by aeosynth** [comment]
i could finish it if you like

**Comment by TheGiddyLimit** [comment]
Go for it, frees me up to work on the JSON.
