### ISSUE TITLE
Problem with displaying statblocks with same name

### ISSUE THREAD

**Issue by futureamnet** [astranauta/astranauta.github.io#248]
Original issue:
> There's an issue when displaying statblocks in bestiary, when there are two entries with the same name. When trying to view the stats of the Redcap from VGM the stats displayed are for the redcap from ToB. 
> 
> How to replicate:
> 1. Go to Bestiary
> 2. Find Redcap (either using search or scrolling)
> 3. Choose Redcap from VGM
> 4. Stats for Redcap from ToB are displayed instead

This issue is prevalent throughout the site, as name data is being used as a "unique" identifier just about everywhere. -TGL

**Comment by TheGiddyLimit** [comment]
sweating.gif

It was only a matter of time until this problem reared it's ugly head, the way we handle linking and IDs is complete arse, frankly, and makes my eyes bleed every time I look at it. This is justification enough for me to spend time overhauling it, but that's not going to be quick.

Temporarily hotfixed Redcap in #255.

**Comment by ixendrax** [comment]
Same issue with Serpopard (ToB, PSA) and Kraken (MM, PSZ) although i think that's all at the moment.
