### ISSUE TITLE
Bestiary: Severin

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#264]
The Legendary Actions section is a bit messed up.

Here's how it currently looks like:

> Legendary Actions
> --
> Severin  can take 3 legendary actions, choosing from the options below. Only one  legendary action can be used at a time and only at the end of another  creature's turn. Severin regains spent legendary actions at the start of  his turn.
> **Attack**. If  Severin is wearing the Mask of the Dragon Queen, he can take 3  legendary actions, choosing from the options listed. Only one legendary  action option can be used at a time and only at the end of another  creature's turn. Severin regains spent legendary actions at the start of  his turn.Severin makes one attack.

Here's how it should be:

> Legendary Actions
> --
> If  Severin is wearing the Mask of the Dragon Queen, he can take 3  legendary actions, choosing from the options listed. Only one legendary  action option can be used at a time and only at the end of another  creature's turn. Severin regains spent legendary actions at the start of  his turn.
> **Attack**. Severin makes one attack.

**Comment by MrLabRat** [comment]
Will fix it!
