### ISSUE TITLE
CR Calc: Parry not working and minor layout issues

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#279]
Ticking the Parry checkbox (Monster features section) should increase the effective
AC by 1 but it is not working.

Since we're here, is it possible to have a better vertical alignment between descriptive
elements and related input fields? For instance, look how "Use saves?" is higher than its
checkbox (Offensive section).

Input fields for Legendary Resistance and Regeneration are too small
(the input field for hit dice has been fixed but those two weren't).

**Comment by Temp345** [comment]
I've fixed **Parry** (still waiting for approval).

I've noticed that, in the Monster Features, **Nimble Escape** include the Shadow Demon as example, but the Shadow Demon has **Shadow Stealth** which only increases the AC, it doesn't also increase the effective attack bonus. It's a minor thing but it could be confusing.

**Comment by MrLabRat** [comment]
This should be fully solved with #294
