### ISSUE TITLE
Bestiary: Half-Red Dragon Veteran. Remove Saving Throws

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#281]
It should not have Saving Throws (see MM Errata).

**Comment by MrLabRat** [comment]
Link to MM Errata? I've searched for it and there's no Half-Red Dragon Veteran entry

**Comment by Temp345** [comment]
http://media.wizards.com/2016/downloads/DND/MM-Errata.pdf

> Half-Dragon (p. 180).  Cut the Saving Throws line and the Parry ability from the stat block.

**Comment by MrLabRat** [comment]
Should be solved in #282
