### ISSUE TITLE
Item List : canoe and airship

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#322]
**canoe** (ToA) listed as magic item with rarity **unknown** (instead of **none**, I guess).

How about adding the **Airship** to the list of vehicles?
Airship | vehicle | DMG | none
Other data:
Cost: 20000 gp
Speed: 8 mph
Crew: 10
Passengers: 20
Cargo (tons): 1
AC: 13
HP: 300
Damage Threshold: -
Source: DMG pag. 119

Maybe you could add it also to the "Mounts and Vehicles" section of the Rules page?
Not sure why it was not included in the PHB, maybe there's a reason behind it?

**Comment by DBAWiseMan** [comment]
I'm doing a big data-cleanse on items.json - I've included those fixes for **Canoe** and have also added **Airship**, but for the moment I've **not** added the DMG-only properties for any vehicle. When I've finally removed all the duplicated text from the JSON I think there will be a review to see what other properties should be added and displayed.
My understanding is that the Rules page is based solely on the SRD. I think there are other things that could be added to it if we expanded beyond the SRD, e.g. Pantheons.
