### ISSUE TITLE
CR Calc Offensive overlay problem

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#336]
When putting your mouse over **Damage Per Round:** and **Uses Saves?** in the Offensive section it doesn't go over correctly. It goes behind the bold text and is mostly unreadable.

**Comment by astranauta** [comment]
https://imgur.com/S3PMGeL

This is what the error looks like. @MrLabRat @TheGiddyLimit Can either of you do something about this?
