### ISSUE TITLE
broken in edge

### ISSUE THREAD

**Issue by commandercrud** [astranauta/astranauta.github.io#394]
Recent changes have broken several pages in Edge that used to work. Spells, psionics, etc. don't work anymore. Bestiary still does.

**Comment by astranauta** [comment]
Trying to support the use of Microsoft Edge will be a game and a half, which is time we can't really commit to it now. I'd recommend using a browser like Firefox or Chrome if you're having issues using the website.
https://www.mozilla.org/en-US/firefox/new/
https://www.google.com/chrome/browser/desktop/index.html

**Comment by commandercrud** [comment]
Cross browser support is not hard. And everything worked fine in Edge until the last week or two.
