### ISSUE TITLE
Item List, Filter by Tier, Major and/or None options give empty list

### ISSUE THREAD

**Issue by Temp345** [astranauta/astranauta.github.io#403]
Is this a bug or a feature request: bug

Issue: when using only the option "Major" for the tier filter, no objects are listed. Same using "None" (even in combination with "Major", the list is empty).

Page(s) affected: items.html

**Comment by DBAWiseMan** [comment]
There aren't any Major items, so that one isn't a bug, #405 will add the "Major, Uncommon" ones.
"None" is a bug, which will get fixed once I've figured out how to handle them in the new filter set-up.
