### ISSUE TITLE
Missing item: Arrow of Slaying

### ISSUE THREAD

**Issue by jrmiller82** [astranauta/astranauta.github.io#471]
DMG pg 152

**Comment by Temp345** [comment]
It's listed as **Ammunition of Slaying**.

The Item List used to have every single variant (e.g. **Adamantine Full Plate Armor**),
but it has relatively recently been changed to only list the generic item (e.g. **Adamantine Armor**).

A minor (?) problem with this new system is that some information is lost.
Example: Adamantine Armor is only for medium and heavy armor (not hide),
but that information is now missing.

**Comment by DBAWiseMan** [comment]
Each item is currently uniquely identified by its combination of name and source. That was fine for every item except **Arrow of Slaying** as both the specific variant that's an arrow (rather that crossbow bolt, etc.) and the generic variant are both in DMG. As the generic variant applies to all types of "Weapon (Arrow)", i.e. "Other types of magic ammunition of this kind exist, such as bolts of slaying meant for a crossbow, though arrows are most common." we chose to call it Ammunition of Slaying to avoid the need to completely rethink how we uniquely identify things. We could have chosen a name like **Arrow of Slaying (Generic)** but it looked messy; it might be less messy to call it **Weapon (Arrow) of Slaying**.
Per the edit, nothing has been lost, but the general feeling was that people didn't like to see all the very numerous variations-on-a-them of magical variants, so they're not displayed by default, c.f. $ types are also hidden by default.

**Comment by jrmiller82** [comment]
That's really confusing when you are in the middle of a game and you want to type in Arrow of Slaying. I get *why* y'all have done it that way, but maybe there should be a FAQ or Errata on the Items page that states the ones that are different from the RAW.
