### ISSUE TITLE
Errata for OotA

### ISSUE THREAD

**Issue by jrmiller82** [astranauta/astranauta.github.io#472]
http://media.wizards.com/2017/dnd/downloads/OotA-Errata.pdf

- [x] Demogorgon's PP needs to be 29 per errata. 

- [x] Grazzt needs skill fixed per errata.

- [x] Orcus needs updating... lair actions and others from text?

- [x] All demon bosses needs updating... lair actions and others from text?

**Comment by MrLabRat** [comment]
We will consider adding Lair actions for all creatures which have it. Closed but noted!
