### ISSUE TITLE
Bunch of errors (I screwed up and put them in the 5etoolsR20 issues.)

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#48]
So I don't know why but I found some errors and reported them on the 5etoolsR20 section when they should have gone here. I'm talking like 2 weeks ago at the longest. I have no clue why I put them there, forgive my stupidity.

**Comment by Buluphont** [comment]
If you could port those issues over to this project, that'd be super for tracking.

**Comment by Konahrik13** [comment]
Infestation and Wild Cunning cantrip spells have bold description text: A majority of Infestation is bold when it shouldn't be along with Wild Cunning, though it's understandable? It looked out of place but I can kinda see why it would be bold.

Severin's Fiery Teleport has wrong number: 1dlO instead of 1d10 again.

Puppet and Sense Emotion spells have incorrect info: Puppet is listed as:
Casting Time: 1 minute
Range: Self

When it should be:
Casting Time: 1 action
Range: 120 feet

Sense Emotion is listed as:
Casting Time: Concentration, up to 10 minutes
Duration: Instantaneous

When it should be:
Casting Time: 1 action
Duration: Concentration, up to 10 minutes

Ancient Black Dragon has a pair of Legendary Resistance (3/Day).: Two where there should be one.

**Comment by Buluphont** [comment]
Everything except the bold text in `Infestation` and `Wild Cunning` to be resolved in #52 . Not too sure what to do about the bolding thing tbh; that's caused probably by some script somewhere parsing text looking for things that look like {cause}: {effect} and bolding it up.
