### ISSUE TITLE
'Book of Lost Spells' not on the list

### ISSUE THREAD

**Issue by LelouchVee** [astranauta/astranauta.github.io#67]
Spells from BoLS don't show up on the list in the Spells section of the web version despite being on the list in spells.json.

**Comment by Jeb-DELETE-THIS-ACCOUNT-EVENTUALLY** [comment]
We have decided to no longer include it in 5etools.

**Comment by astranauta** [comment]
That's incorrect--we removed it for now, but we want to touch base with the team and then the users to figure out what we want to do with it.
