### ISSUE TITLE
Vedalken abilities

### ISSUE THREAD

**Issue by jtarbox** [astranauta/astranauta.github.io#74]
The race Vedalken shows "Int, Wis +1".  It looks like the number for the Int component is missing.  I checked the races.json in the github repo and it is not showing the race.  I honestly don't know the number of the top of my head, but for completion's sake I'm posting this issue for it to be cleaned up.

**Comment by Jeb-DELETE-THIS-ACCOUNT-EVENTUALLY** [comment]
This will be fixed in PR #76
