### ISSUE TITLE
UA-Downtime in rules.json is incomplete

### ISSUE THREAD

**Issue by temp-cardmaker** [astranauta/astranauta.github.io#78]
The UA-Downtime section that appears on the rules page doesn't include anything after "Buying a Magic Item". Some things left out include the Carousing, Crafting a Magic Item, Crime, Gambling, etc.

I get the feeling this might have been intentional, but I didn't see it noted on any other issue.

**Comment by astranauta** [comment]
I was the only one working on it. I took a break from trying to transcribe it a little while ago, and actually intended to pull it off the live website until I had a chance to push a completed version, but didn't get around to doing that either; my apologies for any confusion this has caused.
