### ISSUE TITLE
NPC skill bonuses/proficencies not importing to Roll20 correctly

### ISSUE THREAD

**Issue by ChiefEngineer85** [astranauta/astranauta.github.io#80]
When importing monsters to Roll20, creatures' bonuses/proficencies to skills are not included and must be manually entered. For example, importing an Ancient Silver Dragon does not include its bonuses to Arcana, History, Perception, and Stealth. This issue seems to be present both when using the "OGL by Roll20" sheets as well as the "Shaped" character sheets.

**Comment by astranauta** [comment]
Hmm. The script should only work with the Shaped sheet, as that's what it was originally created to use. I have no experience with coding, but some of the members of my team do--I'll see if they've got the time to glance at the 5etoolsR20 script and see if anything's gone wrong.

**Comment by Konahrik13** [comment]
The Shaped sheet has updated since then if that changes anything, I don't know if screws with how it works.

**Comment by astranauta** [comment]
I think we finally got this solved. Thanks to @MrLabRat for having the commit ready to go, and thanks to TacoSundae for having the fix for me in the first place.
