### ISSUE TITLE
If you need help...

### ISSUE THREAD

**Issue by MrLabRat** [astranauta/astranauta.github.io#82]
I'm a huge D&D fan and my mates and me are using this awesome website.

I have some time on my hands, if you need someone to help you add content to the website, just tell me what needs to be added!

**Comment by astranauta** [comment]
Currently, we need the UA - Revised Class Options to be added to the wiki. I added something like it a little while ago, but I've not been able to update the site according to what it should like. If you want to poke behind the scenes and glance at the code, try to emulate the appearance of what's like and like, then go ahead and take this link to get started. http://media.wizards.com/2017/dnd/downloads/June5UA_RevisedClassOptv1.pdf

Any help is appreciated, by the way, and thanks for using the website. I appreciate it.

**Comment by astranauta** [comment]
Actually, it looks like someone did it for me. Whoops.
