### ISSUE TITLE
Request to add Supernatural Gifts and Epic Boons

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#88]
I think it would be a nice addition to 5etools, though it does come from me running a high level campaign and finding it a pain to go back and forth with the DMG, haha.

**Comment by Olorun** [comment]
Sounds like a nice addition indeed. Any specific place you would want these to show up? I'm thinking of having it in their own subpage under player options.

**Comment by Konahrik13** [comment]
Feels more like it would be under References to me since they're not player focused.

**Comment by MrLabRat** [comment]
https://pastebin.com/raw/5EZ8rm4W

might need some additional proofreading 👍

**Comment by Konahrik13** [comment]
Looks fine to me, though I'm not proficient at knowing how it'll look when it comes up on the site.

**Comment by MrLabRat** [comment]
I'll be submitting it to approval once it's ready. It will take me a couple of days or so.

**Comment by MrLabRat** [comment]
- #89

**Comment by Konahrik13** [comment]
I checked yours and it looks like everything is spelt correctly. My only thought is to have it looks like (Funny enough.) the way the Background, Feats, and Races look rather than a big wall of text. Being able to select what you want and all that.

**Comment by MrLabRat** [comment]
@Konahrik13 I've added all the data to a table. #90 

You can check it at https://mrlabrat.github.io/rewards.html

**Comment by Konahrik13** [comment]
Again, looks good. I don't see any spelling errors but I did just get out of a 9 1/2 hour work day so I'm not quite coherent.

**Comment by astranauta** [comment]
Solved and closed.
