### ISSUE TITLE
Smaragdine Golem in the Beastiary has jumbled stats

### ISSUE THREAD

**Issue by Konahrik13** [astranauta/astranauta.github.io#91]
Its Int, Wis, and Cha are 3 (−4) 11 () 1 (−5) () 10 (), which makes very little sense. Looking at the ToB they should be 3 (−4) 11 (+0) 1 (−5).

**Comment by MrLabRat** [comment]
This should be fixed in the last commit!

**Comment by MrLabRat** [comment]
It should be fixed now! #93
